### ISSUE TITLE
 Current polarity inverted 

### ISSUE THREAD

**Issue by dann2008** [tfyoung/esphome-junctek_kgf#2]
![batt curr history](https://user-images.githubusercontent.com/78565890/195155720-ae5205c2-0f4b-43fe-abfe-03b4c1cdaef4.jpg)

![batt curr](https://user-images.githubusercontent.com/78565890/195156563-90cf22ce-364e-40fd-93af-961c17e5b894.jpg)

The values shown in HA are inverted but on the junktec display polarity is shown correctly

The green side is for Charging + and the red side is discharging -

How can i change polarity ?

**Comment by Quattrohead** [comment]
Hi Dann, are you on diysolarforum ? Would like to chat to you about this on here or there.

**Comment by dann2008** [comment]
Ok, let me now how are your readings 
I had to invert the shunt in order to display correct polarity
But its wrong, because now the battery capacity is inverted
Thank you

**Comment by tfyoung** [comment]
Hi,

I'm still not sure if it's currently right or wrong (my setup has no load connected again yet to test), but I've added the option to change it. there is now an "invert_current" option. It defaults to "false" to match previous behaviour, but once i have things setup and confirm which way i think it should be, then that may change. @dann2008 you definitely want to add the "invert_current: true" line, to get the behaviour you want.

**Comment by dann2008** [comment]
![junktek](https://user-images.githubusercontent.com/78565890/218176544-f8a32e41-86c3-41cb-adac-ec9f3044d197.jpg)
Hi, 

I've just added the  "invert_current: true" line on my config, now the polarity is shown correctly
Values shown in the photo are positive but my battery is discharging, when i'll invert back the shunt it will show the correct values
Thank You !!!
